ALTER TABLE Users
DROP CONSTRAINT FK_Users_CreatedBy;

ALTER TABLE Users
ALTER COLUMN CreatedBy UNIQUEIDENTIFIER NULL;

ALTER TABLE Users
ADD CONSTRAINT FK_Users_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES Users(Id);